apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qmi98o05p-java-quarkus 
  janus-idp.io/tekton: qmi98o05p-java-quarkus
  backstage.io/kubernetes-id: qmi98o05p-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qmi98o05p-java-quarkus
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml